require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

module Phcmembers
  RSpec.describe Connections::MemberaddressesController, type: :controller do

    # This should return the minimal set of attributes required to create a valid
    # Connections::Memberaddress. As you add validations to Connections::Memberaddress, be sure to
    # adjust the attributes here as well.
    let(:valid_attributes) {
      skip("Add a hash of attributes valid for your model")
    }

    let(:invalid_attributes) {
      skip("Add a hash of attributes invalid for your model")
    }

    # This should return the minimal set of values that should be in the session
    # in order to pass any filters (e.g. authentication) defined in
    # Connections::MemberaddressesController. Be sure to keep this updated too.
    let(:valid_session) { {} }

    describe "GET #index" do
      it "assigns all connections_memberaddresses as @connections_memberaddresses" do
        memberaddress = Connections::Memberaddress.create! valid_attributes
        get :index, params: {}, session: valid_session
        expect(assigns(:connections_memberaddresses)).to eq([memberaddress])
      end
    end

    describe "GET #show" do
      it "assigns the requested connections_memberaddress as @connections_memberaddress" do
        memberaddress = Connections::Memberaddress.create! valid_attributes
        get :show, params: {id: memberaddress.to_param}, session: valid_session
        expect(assigns(:connections_memberaddress)).to eq(memberaddress)
      end
    end

    describe "GET #new" do
      it "assigns a new connections_memberaddress as @connections_memberaddress" do
        get :new, params: {}, session: valid_session
        expect(assigns(:connections_memberaddress)).to be_a_new(Connections::Memberaddress)
      end
    end

    describe "GET #edit" do
      it "assigns the requested connections_memberaddress as @connections_memberaddress" do
        memberaddress = Connections::Memberaddress.create! valid_attributes
        get :edit, params: {id: memberaddress.to_param}, session: valid_session
        expect(assigns(:connections_memberaddress)).to eq(memberaddress)
      end
    end

    describe "POST #create" do
      context "with valid params" do
        it "creates a new Connections::Memberaddress" do
          expect {
            post :create, params: {connections_memberaddress: valid_attributes}, session: valid_session
          }.to change(Connections::Memberaddress, :count).by(1)
        end

        it "assigns a newly created connections_memberaddress as @connections_memberaddress" do
          post :create, params: {connections_memberaddress: valid_attributes}, session: valid_session
          expect(assigns(:connections_memberaddress)).to be_a(Connections::Memberaddress)
          expect(assigns(:connections_memberaddress)).to be_persisted
        end

        it "redirects to the created connections_memberaddress" do
          post :create, params: {connections_memberaddress: valid_attributes}, session: valid_session
          expect(response).to redirect_to(Connections::Memberaddress.last)
        end
      end

      context "with invalid params" do
        it "assigns a newly created but unsaved connections_memberaddress as @connections_memberaddress" do
          post :create, params: {connections_memberaddress: invalid_attributes}, session: valid_session
          expect(assigns(:connections_memberaddress)).to be_a_new(Connections::Memberaddress)
        end

        it "re-renders the 'new' template" do
          post :create, params: {connections_memberaddress: invalid_attributes}, session: valid_session
          expect(response).to render_template("new")
        end
      end
    end

    describe "PUT #update" do
      context "with valid params" do
        let(:new_attributes) {
          skip("Add a hash of attributes valid for your model")
        }

        it "updates the requested connections_memberaddress" do
          memberaddress = Connections::Memberaddress.create! valid_attributes
          put :update, params: {id: memberaddress.to_param, connections_memberaddress: new_attributes}, session: valid_session
          memberaddress.reload
          skip("Add assertions for updated state")
        end

        it "assigns the requested connections_memberaddress as @connections_memberaddress" do
          memberaddress = Connections::Memberaddress.create! valid_attributes
          put :update, params: {id: memberaddress.to_param, connections_memberaddress: valid_attributes}, session: valid_session
          expect(assigns(:connections_memberaddress)).to eq(memberaddress)
        end

        it "redirects to the connections_memberaddress" do
          memberaddress = Connections::Memberaddress.create! valid_attributes
          put :update, params: {id: memberaddress.to_param, connections_memberaddress: valid_attributes}, session: valid_session
          expect(response).to redirect_to(memberaddress)
        end
      end

      context "with invalid params" do
        it "assigns the connections_memberaddress as @connections_memberaddress" do
          memberaddress = Connections::Memberaddress.create! valid_attributes
          put :update, params: {id: memberaddress.to_param, connections_memberaddress: invalid_attributes}, session: valid_session
          expect(assigns(:connections_memberaddress)).to eq(memberaddress)
        end

        it "re-renders the 'edit' template" do
          memberaddress = Connections::Memberaddress.create! valid_attributes
          put :update, params: {id: memberaddress.to_param, connections_memberaddress: invalid_attributes}, session: valid_session
          expect(response).to render_template("edit")
        end
      end
    end

    describe "DELETE #destroy" do
      it "destroys the requested connections_memberaddress" do
        memberaddress = Connections::Memberaddress.create! valid_attributes
        expect {
          delete :destroy, params: {id: memberaddress.to_param}, session: valid_session
        }.to change(Connections::Memberaddress, :count).by(-1)
      end

      it "redirects to the connections_memberaddresses list" do
        memberaddress = Connections::Memberaddress.create! valid_attributes
        delete :destroy, params: {id: memberaddress.to_param}, session: valid_session
        expect(response).to redirect_to(connections_memberaddresses_url)
      end
    end

  end
end
